server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: dikidi-api
  client:
    base-url: "https://dikidi.ru"
    connect-timeout: 10_000
    read-timeout: 20_000
resilience4j:
  ratelimiter:
    instances:
      dikidi:
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 5s
